from __future__ import annotations

from typing import Any

DEFAULT_CONFIG: dict[str, Any] = {
    "common": {
        "poppler_path": "",
        "dpi": 240,
        "output_pdf_dpi": 240,
        "jpeg_quality": 92,
        "cpu_processes": 1,
        "quality_profile": "balanced",
        "same_folder": True,
        "overwrite": False,
        "suffix": "_clean",
    },
    "modes": {
        "ebook": {
            "display_name": "Ebook",
            "header_height": "0%",
            "footer_height": "0%",
            "output_grayscale": False,
            "top_template_path": "builtin",
            "bottom_template_path": "builtin",
            "diag_template_path": "builtin",
            "top_threshold": 0.55,
            "bottom_threshold": 0.55,
            "diag_threshold": 0.25,
            "protect_gray_threshold": 105,
            "min_matched_regions": 1,
            "graph_safe_paper_mode": False,
            "ebook_skip_color_cover_page": True,
            "ebook_ghost_cleanup": True,
            "ebook_ghost_strength": 0.66,
            "ebook_ghost_gray_min": 138,
            "ebook_ghost_gray_max": 246,
            "ebook_ghost_sat_max": 56,
            "ebook_ghost_band_ratio": 0.128,
            "ebook_ghost_content_dark_gray": 158,
            "ebook_ghost_colored_sat_min": 38,
            "ebook_ghost_edge_dilate": 3,
            "ebook_ghost_mask_dilate": 2,
            "ebook_ghost_bg_median_kernel": 35,
            "ebook_ghost_bg_gauss_sigma": 7.0,
            "ebook_ghost_max_darken_to_bg": 55,
            "ebook_ghost_require_local_darker": True,
            "ebook_ghost_local_diff_min": 2,
            "ebook_ghost_local_diff_max": 70,
            "ebook_cover_color_area_min": 0.22,
            "ebook_cover_paper_area_max": 0.78,
            "output_mode": "full_raster",
            "full_raster_format": "png",
            "fallback_image_format": "png",
        },
        "ly": {
            "display_name": "Lý - IPCLASS",
            "tailieuonthi_cleanup": "strong",
            "tailieuonthi_stream_preredact": True,
            "tailieuonthi_stream_preredact_scope": "safe",
            "tailieuonthi_image_cleanup": True,
            "tailieuonthi_diag_width_ratio": 0.060,
            "tailieuonthi_top_ratio": 0.055,
            "tailieuonthi_bottom_ratio": 0.055,
            "header_height": "3%",
            "footer_height": "3%",
            "output_grayscale": False,
            "keep_sat_lower": "0,80,0",
            "keep_sat_upper": "179,255,255",
            "preserve_illustrations": False,
            "aggressive_white": True,
            "background_saturation_upper": 65,
            "graph_preserve_enabled": True,
            "graph_faint_gray_max": 238,
            "graph_neutral_sat_max": 96,
            "graph_local_contrast_min": 4,
            "graph_canny_low": 22,
            "graph_canny_high": 88,
            "graph_line_min_len": 22,
            "graph_dashed_close_px": 15,
            "graph_near_line_dilate_px": 24,
            "graph_protect_dilate_px": 2,
            "graph_pale_color_sat_min": 12,
            "graph_pale_color_spread_min": 8,
            "ly_watermark_cleanup_enabled": True,
            "ly_watermark_gray_min": 112,
            "ly_watermark_gray_max": 248,
            "ly_watermark_sat_max": 135,
            "ly_watermark_spread_max": 105,
            "ly_watermark_dark_guard_gray": 135,
            "ly_watermark_dilate_px": 1,
            "output_mode": "full_raster",
            "full_raster_format": "png",
            "fallback_image_format": "png",
        },
        "toan": {
            "display_name": "Toán - TDM V7.6.9 Safe Graph Restore",
            "header_height": "0%",
            "footer_height": "0%",
            "output_grayscale": False,
            "top_template_path": "builtin",
            "bottom_template_path": "builtin",
            "diag_template_path": "builtin",
            "top_threshold": 0.55,
            "bottom_threshold": 0.55,
            "diag_threshold": 0.25,
            "protect_gray_threshold": 105,
            "min_matched_regions": 1,
            "graph_safe_paper_mode": True,
            "tdm_engine_version": "v7.6.9_safe_graph_restore_roi_only",

            "output_mode": "hybrid_auto",
            "full_raster_format": "png",
            "fallback_image_format": "png",
            "hybrid_diff_threshold": 4,
            "hybrid_color_diff_threshold": 7,
            "hybrid_white_gain_threshold": 5,
            "hybrid_line_gain_threshold": 3,
            "hybrid_mask_close_x": 7,
            "hybrid_mask_close_y": 5,
            "hybrid_mask_dilate_px": 2,
            "hybrid_patch_padding_px": 8,
            "hybrid_patch_alpha": "hard",
            "hybrid_alpha_feather_px": 0,
            "hybrid_min_component_area": 10,
            "hybrid_merge_gap_px": 10,
            "hybrid_max_patches": 140,
            "hybrid_max_changed_ratio": 0.42,
            "hybrid_max_patch_coverage": 0.90,
            "hybrid_vector_line_overlay": "false",
            "hybrid_vector_remove_from_raster": True,
            "hybrid_vector_line_gain": 3,
            "hybrid_vector_line_min_width_px": 40,
            "hybrid_vector_line_max_height_px": 4,
            "hybrid_vector_line_opacity": 0.45,
            "header_right_protect": True,
            "header_right_protect_x_min": 0.635,
            "header_right_protect_x_max": 0.995,
            "header_right_protect_y_min": 0.000,
            "header_right_protect_y_max": 0.048,
            "diag_band_width_px": 0,
            "diag_x_min": 0.50,
            "diag_x_max": 0.998,
            "diag_y_min": 0.48,
            "diag_y_max": 0.998,
            "line_restore": True,
            "line_gap_bridge": True,
            "line_gap_bridge_close_x": 260,
            "line_gap_bridge_damage_dilate_x": 150,
            "line_gap_bridge_y_radius": 1,
            "line_gap_bridge_min_clean_pixels": 18,
            "line_gap_bridge_gray_min": 168,
            "line_gap_bridge_sat_max": 135,
            "line_gap_bridge_spread_max": 70,
            "line_gap_bridge_text_gray_max": 178,
            "line_gap_bridge_text_dilate_x": 9,
            "line_global_reconstruction": True,
            "line_global_full_page": False,
            "line_restore_scope": "watermark_roi_only",
            "line_global_y_radius": 1,
            "line_global_blank_gray_min": 162,
            "line_global_blank_sat_max": 150,
            "line_global_blank_spread_max": 80,
            "line_global_missing_gray_min": 236,
            "line_global_missing_sat_max": 150,
            "line_global_missing_spread_max": 85,
            "line_global_damage_dilate_x": 180,
            "line_global_damage_dilate_y": 5,
            "line_global_text_gray_max": 170,
            "line_global_colored_ink_sat_min": 36,
            "line_global_colored_ink_gray_max": 238,
            "line_global_edge_canny_low": 24,
            "line_global_edge_canny_high": 96,
            "line_global_edge_gray_max": 160,
            "line_global_fill_gray_min": 135,
            "line_global_fill_sat_min": 12,
            "line_global_fill_spread_min": 5,
            "line_global_fill_close_x": 11,
            "line_global_fill_close_y": 7,
            "line_global_guard_dilate_x": 5,
            "line_global_guard_dilate_y": 3,
            "line_global_guard_min_area": 2,
            "line_global_min_run_px": 2,
            "line_global_min_confidence": 0.54,
            "line_global_aggressive_confidence": 0.70,
            "graph_restore_enabled": True,
            "graph_roi_dilate_x": 6,
            "graph_roi_dilate_y": 3,
            "graph_restore_min_roi_pixels": 40,
            "graph_restore_min_pixels": 4,
            "graph_restore_min_evidence_pixels": 12,
            "graph_restore_min_confidence": 0.05,
            "graph_restore_dilate": True,
            "graph_table_exclude_dilate_x": 24,
            "graph_table_exclude_dilate_y": 16,
            "graph_table_border_min_len_x": 34,
            "graph_table_border_min_len_y": 34,
            "graph_black_gray_max": 120,
            "graph_black_aa_gray_max": 170,
            "graph_black_weaken_diff": 10,
            "graph_edge_canny_low": 24,
            "graph_edge_canny_high": 105,
            "graph_line_min_len": 28,
            "graph_dashed_close_px": 17,
            "graph_blue_hue_min": 88,
            "graph_blue_hue_max": 142,
            "graph_blue_sat_min": 35,
            "graph_blue_sat_min_alt": 25,
            "graph_blue_sat_min_clean": 25,
            "graph_blue_gray_max": 245,
            "graph_blue_b_minus_r_min": 20,
            "graph_blue_b_minus_g_min": 5,
            "graph_blue_min_component_area": 8,
            "graph_blue_min_component_span": 9,
            "graph_blue_weaken_diff": 10,
            "graph_blue_sat_loss": 12,
            "graph_restore_markers": True,
            "graph_marker_gray_max": 130,
            "graph_marker_min_area": 3,
            "graph_marker_max_area": 180,

            "table_aware_cleanup": True,
            "table_cell_gray_min": 165,
            "table_cell_value_min": 168,
            "table_cell_sat_min": 8,
            "table_cell_sat_max": 135,
            "table_cell_spread_min": 5,
            "table_cell_min_area": 250,
            "table_cell_min_width_px": 12,
            "table_cell_min_height_px": 12,
            "table_cell_max_width_ratio": 0.24,
            "table_cell_max_height_ratio": 0.40,
            "table_cell_min_coverage": 0.22,
            "table_cell_min_sample_pixels": 40,
            "table_cell_min_band_pixels": 6,
            "table_cell_min_color_spread": 5.0,
            "table_band_intersect_dilate_x": 13,
            "table_band_intersect_dilate_y": 7,
            "table_near_dilate_x": 18,
            "table_near_dilate_y": 10,
            "table_bg_patch_alpha": 1.0,
            "table_bg_patch_gray_min": 155,
            "table_bg_patch_sat_max": 180,
            "table_bg_patch_spread_max": 120,
            "table_bg_patch_diag_dilate_x": 13,
            "table_bg_patch_diag_dilate_y": 5,
            "table_stroke_gray_max": 185,
            "table_stroke_sat_min": 70,
            "table_stroke_color_gray_max": 225,
            "table_border_min_len_x": 28,
            "table_border_min_len_y": 28,
            "table_circle_canny_low": 35,
            "table_circle_canny_high": 120,
            "table_compact_stroke_min_area": 8,
            "table_compact_stroke_max_area": 2200,
            "table_compact_stroke_max_w": 95,
            "table_compact_stroke_max_h": 95,
            "table_restore_stroke_dilate": True,
        },
        "hoa": {
            "display_name": "Hóa - TYHH",
            "stream_only": True,
            "markers": [
                "TAILIEUONTHI.NET",
                "TaiLieuOnThi.Net",
                "TaiLieuOnThi",
                "TAILIEUONTHI",
                "Tai Lieu On Thi",
                "Tài Liệu Ôn Thi Group"
            ],
            "allow_stream_auto": False,
            "header_height": "0%",
            "footer_height": "0%",
            "output_grayscale": False,
        },
    },
}


QUALITY_PRESETS: dict[str, dict[str, int]] = {
    "fast": {"dpi": 200, "output_pdf_dpi": 200, "jpeg_quality": 88, "cpu_processes": 1},
    "balanced": {"dpi": 240, "output_pdf_dpi": 240, "jpeg_quality": 92, "cpu_processes": 1},
    "high_quality": {"dpi": 320, "output_pdf_dpi": 320, "jpeg_quality": 95, "cpu_processes": 1},
    "safe_mode": {"dpi": 240, "output_pdf_dpi": 240, "jpeg_quality": 95, "cpu_processes": 1},
}
